apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joshlong-site
  name: joshlong-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joshlong-site
  template:
    metadata:
      labels:
        app: joshlong-site
    spec:
      containers:
        - image: gcr.io/joshlong/joshlong-site
          imagePullPolicy: Always
          name: joshlong-site
          env:
            - name: PORT
              value: "8080"
