apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "joshlong-com-site-ip"
#    ingress.kubernetes.io/force-ssl-redirect: "true"
#    networking.gke.io/managed-certificates: "joshlong-site-certificate"
  name: site-ingress
spec:
  rules:
  - host: joshlong.com
    http:
      paths:
      - backend:
          serviceName: site
          servicePort: 80
