name: Deploy

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: joshlong-com
  GKE_ZONE: us-central1-c
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}


on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: google-github-actions/setup-gcloud@v0

      - run: |
          gcloud config set project $PROJECT_ID
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
          kubectl get pods
          gcloud compute addresses list --format json  

