name: Deploy

env:
  API_ROOT: https://api.joshlong.com
  APP_NAME: joshlong-site

  ##
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE }}
  GCLOUD_PROJECT: joshlong
  NS_NAME: ${{ secrets.NS_NAME }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"

    name: Setup and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup PATH"
        run: |
          P="${GITHUB_WORKSPACE}/bin"
          mkdir -p $P
          echo "${P}" >> $GITHUB_PATH

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER  }}"
          location: "${{ env.GCLOUD_ZONE }}"

      - run: |
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker us-docker.pkg.dev
          kubectl get pods

      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Publish Container
        run: |
          export PATH=$GITHUB_WORKSPACE/bin/:$PATH
          mkdir -p $GITHUB_WORKSPACE/bin/
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-linux.tgz" | sudo tar -C  $GITHUB_WORKSPACE/bin/ --no-same-owner -xzv pack)
          export APP_NAME=joshlong-site
          export IMAGE_NAME="us-docker.pkg.dev/joshlong/developer-advocacy-artifact-registry/${APP_NAME}:latest"
          export ROOT_DIR=$GITHUB_WORKSPACE
          $GITHUB_WORKSPACE/deploy/deploy.sh

      # - id: "get-credentials"
      #   uses: "google-github-actions/get-gke-credentials@v1"
      #   with:
      #     cluster_name: "${{ env.GKE_CLUSTER  }}"
      #     location: "${{ env.GCLOUD_ZONE }}"

      # - run: |
      #     gcloud config set project $GCLOUD_PROJECT
      #     gcloud --quiet auth configure-docker us-docker.pkg.dev
      #     kubectl get pods

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: Deploy Site
      #   run: |
      #     kubectl get ns/$NS_NAME || kubectl create ns $NS_NAME
      #     kubectl config set-context --current --namespace=$NS_NAME
      #     kubectl config view --minify | grep "namespace:" && echo "found the namespace.."
      #     cd $GITHUB_WORKSPACE
      #     export PATH=$GITHUB_WORKSPACE/bin/:$PATH
      #     mkdir -p $GITHUB_WORKSPACE/bin/
      #     (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-linux.tgz" | sudo tar -C  $GITHUB_WORKSPACE/bin/ --no-same-owner -xzv pack)
      #     export ROOT_DIR=$GITHUB_WORKSPACE
      #     ./deploy/deploy.sh
